name: Stats

on: 
  push: 
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run script
        run: python stats.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with: 
          commit_message: Update stats
          commit_user_name: Patrick
